FROM nginx:alpine

COPY ssl-params.conf /etc/nginx/ssl-params.conf

COPY nginx.conf /home/tracevia/app/applications/docker/nginx/nginx.conf
COPY conf.d/ /home/tracevia/app/applications/docker/nginx/conf.d/
;COPY sites-available/ /home/tracevia/app/applications/docker/nginx/sites-available/
;COPY sites-enabled/ /home/tracevia/app/applications/docker/nginx/sites-enabled/

RUN mkdir -p /etc/nginx/certs

EXPOSE 80 443 5173

CMD ["nginx", "-g", "daemon off;"]
